
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      before_install:
        - git clone https://github.com/IBM-Swift/Package-Builder.git
      script: ./Package-Builder/build-package.sh -projectDir $TRAVIS_BUILD_DIR
    - os: osx
      osx_image: xcode10.2
      sudo: required
      language: objective-c
      env: TEST_DESTINATION="OS=12.2,name=iPhone X"
      install:
        - ./install_swiftlint.sh
      script:
        - set -o pipefail && xcodebuild test -workspace Example/SwiftyHYGDB.xcworkspace -scheme SwiftyHYGDB-Example -destination "$TEST_DESTINATION" | xcpretty
